version: '3.1'
services:
  db:
    image: mysql
    container_name: flashcards_mysql
    env_file:
      - ../.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:?err}
      MYSQL_DATABASE: ${DB_NAME}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      - ./volumes/mysql:/var/lib/mysql
  adminer:
    image: adminer
    container_name: flashcards_adminer
    ports:
      - 8080:8080
